name: open-games-hs
version: '0.1.0.0'
synopsis: Haskell implementation of open games
category: Math
author: Jules Hedges, André Videla, Philipp Zahn & other contributors
maintainer: philipp.zahn@protonmail
copyright: Jules Hedges, André Videla, Philipp Zahn & other contributors
license: AGPL
extra-source-files:
- README.md


library:
  source-dirs: src
  exposed-modules:
    - Engine.BayesianGames
    - Engine.Diagnostics
    - Engine.Engine
    - Engine.OpenGames
    - Engine.OpticClass
    - Engine.QLearning
    - Engine.QLearning.Export
    - Engine.QLearningSimple
    - Engine.TLL
    - Preprocessor.AbstractSyntax
    - Preprocessor.Compile
    - Preprocessor.Lambda
    - Preprocessor.Parser
    - Preprocessor.THSyntax
    - Preprocessor.TH
    - Preprocessor.Types
    - Preprocessor.Preprocessor
    - Examples.SimultaneousMoves
    - Examples.Bayesian
    - Examples.Decision
    - Examples.SequentialMoves
    - Examples.QLearning.PD
    - Examples.QLearning.PDDeterministicPlayer
    - Examples.QLearning.SandholmCritesReplication
    - Examples.QLearning.CalvanoReplication
    - Examples.QLearning.CalvanoReplication.Internal
    - Examples.QLearning.BestReply

dependencies:
    - base >=4.7 && <5
    - mtl
    - transformers
    - ad
    - poly
    - profunctors
    - template-haskell
    - parsec
    - comonad
    - optics
    - ixset
    - random-fu
    - probability
    - hashtables
    - random
    - vector
    - unordered-containers
    - mwc-random >= 0.15.0.1
    - vector-sized
    - hashable
    - cassava
    - bytestring
    - aeson
    - filepath
    - typed-process
    - clock
    - rio
    - formatting
    - deepseq
    - array
    - time
    - containers
    - path
    - path-io
    - unliftio
    - double-conversion

executables:
  learning-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
      - open-games-hs
  game:
    main:                Main.hs
    source-dirs:         game
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall

tests:
  test-open-games:
    buildable: True
    main: Spec
    source-dirs: tests
    dependencies:
      - open-games-hs
      - template-haskell
      - base
      - hspec

benchmarks:
  learning-bench:
    main:                Main.hs
    source-dirs:         bench
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -eventlog
    dependencies:
      - open-games-hs
      - criterion
