name: open-games-hs
version: '0.1.0.0'
synopsis: Haskell implementation of open games
category: Math
author: Jules Hedges, André Videla, Philipp Zahn & other contributors
maintainer: philipp.zahn@protonmail
copyright: Jules Hedges, André Videla, Philipp Zahn & other contributors
license: AGPL
github: https://github.com/philipp-zahn/open-games-hs
extra-source-files:
- README.md


library:
  source-dirs: src
  exposed-modules:
    - Engine.BayesianGames
    - Engine.Diagnostics
    - Engine.OpenGames
    - Engine.OpticClass
    - Engine.QLearning
    - Engine.QLearningHash
    - Engine.TLL
    - Preprocessor.AbstractSyntax
    - Preprocessor.Compile
    - Preprocessor.Lambda
    - Preprocessor.Parser
    - Preprocessor.THSyntax
    - Preprocessor.TH
    - Preprocessor.Types
    - Examples.Bimatrix
    - Examples.Bayesian
    - Examples.Sequential
    - Examples.QLearning.PD
    - Examples.QLearning.PDDeterministicPlayer
    - Examples.QLearning.SandholmCritesReplication
    - Examples.QLearning.CalvanoReplication
    - Examples.QLearning.CalvanoReplicationHash
    - Examples.QLearning.CalvanoReplicationMutable
    - Examples.QLearning.CalvanoReplicationHashMutable
    - Examples.QLearning.CalvanoReplicationHashMutableVec
    - Examples.QLearning.BestReply

dependencies:
    - base >=4.7 && <5
    - mtl
    - transformers
    - ad
    - poly
    - profunctors
    - template-haskell
    - parsec
    - comonad
    - optics
    - ixset
    - random-fu
    - probability
    - hashtables
    - random
    - vector
    - unordered-containers
    - mwc-random >= 0.15.0.1
    - hashable
    - cassava
    - bytestring
    - aeson
    - deepseq
    - array

executables:
  learning-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
      - open-games-hs

tests:
  test-open-games:
    buildable: False
    main: THTests
    source-dirs: tests
    dependencies:
      - template-haskell
      - base
      - hspec
  golden-tests:
    main: GoldenTests
    source-dirs: tests
    other-modules: GoldenTests
    dependencies:
      - template-haskell
      - base
      - hspec
      - open-games-hs

benchmarks:
  learning-bench:
    main:                Main.hs
    source-dirs:         bench
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -eventlog
    dependencies:
      - open-games-hs
      - criterion
