name: Analyze

on:
  workflow_dispatch:
    inputs:
      run-id:
        description: 'The run ID for the learning file'
        required: true
        default: ''

jobs:
  analyze:
    runs-on: [self-hosted, cpu]

    steps:
      - uses: actions/checkout@v2

      - name: Try to login to docker hub registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      # Remember to update this hash whenever you update your R dependencies in any way
      - name: Run analysis process
        env:
          LEARN_RUNID: ${{ github.event.inputs.learn-run-id }}
        run: |
          echo Workflow was run with input: learn-run-id=$LEARN_RUNID

          # Grab experiment outputs
          LEARN_FILENAME=$LEARN_RUNID-learn.tar.gz
          ARCHIVE_LEARN=$(pwd)/$LEARN_FILENAME

          # Setup directories
          mkdir experiment
          mkdir outputs

          # Download & unpack learning output
          mkdir extraction
          time s3cmd get s3://pricing-game/$LEARN_FILENAME $ARCHIVE_LEARN
          cd extraction
          tar xzf $ARCHIVE_LEARN
          cd ..
          mv extraction/*/* experiment/
          rm -r extraction
          # End of experiment extraction

          # Setup working directory
          ARCHIVE_ANALYSIS=$(pwd)/$GITHUB_RUN_ID-analysis.tar.gz
          WORKDIR=~/run/$GITHUB_RUN_ID
          sudo mkdir -p $WORKDIR $JOBDIR
          sudo cp -r . $WORKDIR/

          # Run job
          docker run \
            -v$WORKDIR/outputs:/outputs \
            -v$WORKDIR/Rscripts:/Rscripts \
            -v$WORKDIR/experiment:/experiment \
            --rm \
            ghcr.io/learning-games/r:2021-12-07 \
            R -f /Rscripts/asymlearners_robustness.R

          echo Behold, the outputs are...
          ls -alh $WORKDIR/outputs

          # Archive output
          PW=$(pwd)
          cd $WORKDIR/outputs
          time tar czf $ARCHIVE_ANALYSIS .
          cd $PW

          # Upload output
          time s3cmd put $ARCHIVE_ANALYSIS s3://pricing-game/

          # Wipe working directory
          sudo rm -rf $WORKDIR
