name: Test self-hosted runner

on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Do not change'
        required: true
        default: 'dummy input'
      tags:
        description: 'dummy input, ignore'

jobs:
  push:
    runs-on: self-hosted-ubuntu-with-docker

    steps:
      - uses: actions/checkout@v2

      - name: Test action
        run: echo OK

      - name: Test whether docker works
        run: docker --version


      - name: Try to login to docker hub registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
